services:
  roscore:
    image: uos-robotics:latest
    container_name: roscore
    command: roscore
    network_mode: host
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
    restart: always
  rosdev:
    image: uos-robotics:latest
    container_name: rosdev
    network_mode: host
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=host.docker.internal:0
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - ./labs:/workspace/labs
      - ./ros.mk:/Makefile
      - ./catkin_ws:/workspace/catkin_ws
    command: [ "/bin/bash", "-c", "echo 'source /opt/ros/melodic/setup.bash' >> ~/.bashrc && source ~/.bashrc && tail -f /dev/null" ]
    restart: always
