services:
  roscore:
    image: uos-robotics:latest
    container_name: roscore
    command: roscore
    network_mode: host
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
    restart: always
  rosdev:
    image: uos-robotics:latest
    container_name: rosdev
    network_mode: host
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./labs:/workspace
    command: [ "/bin/bash", "-c", "echo 'source /opt/ros/melodic/setup.bash' >> ~/.bashrc && source ~/.bashrc && tail -f /dev/null" ]
    restart: always
