services:
  roscore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roscore
    command: roscore
    networks:
      - rosnet
    environment:
      - ROS_HOSTNAME=roscore
      - ROS_MASTER_URI=http://roscore:11311
    restart: always

  rosdev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosdev
    ports:
      - "5901:5901"
      - "6080:6080"
    networks:
      - rosnet
    environment:
      - ROS_HOSTNAME=rosdev
      - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - ./ros.mk:/root/catkin_ws/Makefile
      - ./catkin_ws:/root/catkin_ws
      - ./labs:/root/labs
    restart: always

networks:
  rosnet:
    driver: bridge
