services:
  roscore:
    image: uos-robotics:latest
    container_name: roscore
    command: roscore
    networks:
      - ros_net
    environment:
      - ROS_HOSTNAME=roscore
      - ROS_MASTER_URI=http://roscore:11311
    restart: always

  rosdev:
    image: uos-robotics:latest
    container_name: rosdev
    ports:
      - "5901:5901"
      - "6080:6080"
    networks:
      - ros_net
    environment:
      - ROS_HOSTNAME=rosdev
      - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - ./ros.mk:/Makefile
      - ./catkin_ws:/root/catkin_ws
    restart: always

networks:
  ros_net:
    driver: bridge
