services:
  roscore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roscore
    command: roscore
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    restart: always

  rosdev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosdev
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ../catkin_ws:/root/catkin_ws
    restart: always